config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :players, only: [:index]
  resources :games, only: [:index]
  resources :search, only: [:index]

  # Defines the root path route ("/")
  root 'search#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    name = permitted_params[:name]

    render json:search_players(name)
  end

  private

  def permitted_params
    params.permit(:name)
  end

  def search_players(name)
    aoeworld_users = Aoeworld.instance.players(name)

    aoeworld_users.map do |user|
      {
        id: user["profile_id"],
        name: user['name']
      }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search_params = search_permitted_params[:search] || {}

    @player = search_player(search_params[:player])
    @opponent = search_player(search_params[:opponent])
    @games = search_games(search_params[:player], search_params[:opponent])
  end

  private

  def search_games(player, opponent)
    return if player.blank? || opponent.blank?

    Aoeworld.instance.games(
      player_id: player,
      opponent_id: opponent
    )
  end

  def search_player(id)
    Aoeworld.instance.player(id.to_i)
  end

  def search_permitted_params
    params.permit(search: [:player, :opponent])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def player_data_to_collection(player_data)
    [
      [
        player_data['name'], player_data['profile_id']
      ]
    ]
  end

  def game_url(player:, game_id:)
    "#{Aoeworld::AOE4WORLD_URL}/players/#{player['profile_id']}/games/#{game_id}"
  end

  def player_url(player_id)
    "#{Aoeworld::AOE4WORLD_URL}/players/#{player_id}"
  end
end

app/views/home/index.html.erb
<main class="container">
  <%= simple_form_for(
      :search,
      defaults: {
        input_html: { class: "input" },
        label_html: { class: "label" },
        required: false,
        wrapper_html: { class: 'field' }
      }
    )  do |f| %>
    <%= f.input :player, input_html: { autofocus: true } %>
    <%= f.input :opponent %>
    <%= f.submit "Search", class: "button is-primary"  %>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Have we dented?</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/tom-select/dist/css/tom-select.css", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div>
      <h1 class="title is-size-1 has-text-centered">Have we dented?</h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/search/_game.html.erb
<% game = local_assigns[:game] %>

<div class="box has-background-grey-lighter">
  <div class="columns">
    <div class="column has-text-left has-text-weight-bold">
      <span class="icon">
        <i class="fa-solid fa-magnifying-glass"></i>
      </span>
      <%= link_to "View game summary", game_url(player: @player, game_id: game['game_id']), class: "has-text-black" %>
    </div>

    <div class="column has-text-right has-text-weight-bold">
      <%= game['started_at'].to_date.strftime("%d %b %Y") %>
    </div>
  </div>

  <div class="columns has-background-white has-text-centered is-flex is-vcentered">
    <% game['teams'].each_with_index do |players, team_index| %>
      <% unless team_index.zero? %>
        <div class="column">
          <span class="icon">
            <i class="fa-solid fa-x"></i>
          </span>
        </div>
      <% end %>

      <div class="column">
        <% players.each do |player_info| %>
          <% player = player_info['player'] %>
          <% player_classes = player['result'] == 'win' ? 'has-text-success' : 'has-text-danger' %>

          <div class="block">
            <%= link_to player['name'], player_url(player['profile_id']), class: player_classes %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/search/_no_result.erb
<div>
  No games found!
</div>

app/views/search/index.html.erb
<main class="container">
  <%= simple_form_for(
      :search,
      method: :get,
      html: {
        class: 'block',
        data: {
          turbo_frame: 'game_list',
          turbo_action: 'advance',
          controller: 'form',
          action: 'input->form#submit'
        }
      }
    )  do |f| %>

    <div class="field">
      <%= f.label :player, class: "label", required: false%>
      <%= f.select :player, player_data_to_collection(@player), {}, { data: { controller: "select", select_url_value: players_path }} %>
    </div>

    <div class="field">
      <%= f.label :opponent, class: "label", required: false%>
      <%= f.select :opponent, player_data_to_collection(@opponent), {}, { data: { controller: "select", select_url_value: players_path }} %>
    </div>


    <%= f.submit "Search", class: "button is-primary", name: "" %>
  <% end %>

  <%= turbo_frame_tag "game_list" do %>
    <% if @games.is_a?(Array) %>
      <% if @games.any? %>
        <div class="block">
          <%= render partial: 'search/game', collection: @games %>
        </div>
      <% else %>
        <%= render partial: 'search/no_result' %>
      <% end%>
    <% end%>
  <% end %>
</main>